# This file contains the properties with key and values 

appURL=http://localhost/orangehrm/web/index.php/auth/login
implicitWaitTime=10
fluentWaitTime=80
userName=admin
password=Welcome@1234$
dbConnectionString=